/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package burnmagno;

/**
 *
 * @author Jong's TV
 */
public class j1 extends javax.swing.JFrame {

    /**
     * Creates new form j1
     */
    public j1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        j1 = new javax.swing.JButton();
        j2 = new javax.swing.JButton();
        JL1 = new javax.swing.JLabel();
        JL2 = new javax.swing.JLabel();
        JL3 = new javax.swing.JLabel();
        JLBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j1.setBackground(new java.awt.Color(255, 255, 255));
        j1.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        j1.setText("START");
        j1.setAlignmentY(0.0F);
        j1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        j1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        j1.setIconTextGap(0);
        j1.setVerifyInputWhenFocusTarget(false);
        j1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        j1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });
        jPanel2.add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 120, 40));
        j1.getAccessibleContext().setAccessibleDescription("");

        j2.setBackground(new java.awt.Color(255, 255, 255));
        j2.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        j2.setText("EXIT");
        j2.setAlignmentY(0.0F);
        j2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        j2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        j2.setIconTextGap(0);
        j2.setVerifyInputWhenFocusTarget(false);
        j2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        j2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });
        jPanel2.add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 120, 40));

        JL1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        JL1.setForeground(new java.awt.Color(255, 255, 255));
        JL1.setText("DATABASE");
        jPanel2.add(JL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 200, 60));

        JL2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        JL2.setForeground(new java.awt.Color(255, 255, 255));
        JL2.setText("STUDENT-ATTENDANCE");
        jPanel2.add(JL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 430, 60));

        JL3.setBackground(new java.awt.Color(255, 255, 255));
        JL3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        JL3.setForeground(new java.awt.Color(255, 255, 255));
        JL3.setText("WELCOME TO THE");
        jPanel2.add(JL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 330, 60));

        JLBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jong's TV\\Desktop\\Untitled design (1).png")); // NOI18N
        jPanel2.add(JLBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        // TODO add your handling code here:
        j2 a = new j2();
        a.show();
        dispose();
    }//GEN-LAST:event_j1ActionPerformed

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_j2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(j1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(j1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(j1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(j1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new j1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL1;
    private javax.swing.JLabel JL2;
    private javax.swing.JLabel JL3;
    private javax.swing.JLabel JLBackground;
    private javax.swing.JButton j1;
    private javax.swing.JButton j2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
