/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package burnmagno;

/**
 *
 * @author Jong's TV
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class j3 extends javax.swing.JFrame {

    /**
     * Creates new form j3
     */
    public j3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        JSTUDENT = new javax.swing.JLabel();
        ju1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        ju2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        ju3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        ju4 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        ju5 = new javax.swing.JLabel();
        jb1 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();
        jb4 = new javax.swing.JButton();
        jBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JSTUDENT.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JSTUDENT.setForeground(new java.awt.Color(204, 204, 204));
        JSTUDENT.setText("STUDENT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JSTUDENT, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JSTUDENT, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 600, 40));

        ju1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ju1.setForeground(new java.awt.Color(255, 255, 255));
        ju1.setText("I.D Number:");
        jPanel1.add(ju1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 130, 30));

        t1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 130, 30));

        ju2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ju2.setForeground(new java.awt.Color(255, 255, 255));
        ju2.setText("Firstname:");
        jPanel1.add(ju2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 130, 30));

        t2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 310, 30));

        ju3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ju3.setForeground(new java.awt.Color(255, 255, 255));
        ju3.setText("Lastname:");
        jPanel1.add(ju3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 130, 30));

        t3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        jPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 310, 30));

        ju4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ju4.setForeground(new java.awt.Color(255, 255, 255));
        ju4.setText("Email:");
        jPanel1.add(ju4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 130, 30));

        t4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        jPanel1.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 310, 30));

        t5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        jPanel1.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 310, 30));

        ju5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ju5.setForeground(new java.awt.Color(255, 255, 255));
        ju5.setText("Contact No.:");
        jPanel1.add(ju5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 130, 30));

        jb1.setBackground(new java.awt.Color(255, 255, 255));
        jb1.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        jb1.setText("ADD");
        jb1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });
        jPanel1.add(jb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 120, 30));

        jb2.setBackground(new java.awt.Color(255, 255, 255));
        jb2.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        jb2.setText("UPDATE");
        jb2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });
        jPanel1.add(jb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 120, 30));

        jb3.setBackground(new java.awt.Color(255, 255, 255));
        jb3.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        jb3.setText("DELETE");
        jb3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3ActionPerformed(evt);
            }
        });
        jPanel1.add(jb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 120, 30));

        jb4.setBackground(new java.awt.Color(255, 255, 255));
        jb4.setFont(new java.awt.Font("Centaur", 0, 10)); // NOI18N
        jb4.setText("BACK TO MAIN MENU");
        jb4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb4ActionPerformed(evt);
            }
        });
        jPanel1.add(jb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 150, 30));

        jBackground.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jong's TV\\Documents\\bburn\\JJJ1.png")); // NOI18N
        jPanel1.add(jBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
        // TODO add your handling code here:
        j2 a = new j2();
        a.show();
        dispose();
    }//GEN-LAST:event_jb4ActionPerformed

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        // TODO add your handling code here:
        String URL = "jdbc:derby://localhost:1527/C:/Database/SAdb";
        String query = "insert into STUDENT(Stud_id, fname, lname, email, contactnumber) Values(?,?,?,?,?)";
        
        try{
            Connection z = DriverManager.getConnection(URL);
            PreparedStatement p = z.prepareStatement(query);
            
            p.setString(1, t1.getText());
            p.setString(2, t2.getText());
            p.setString(3, t3.getText());
            p.setString(4, t4.getText());
            p.setString(5, t5.getText());
            
            p.executeUpdate();
            JOptionPane.showMessageDialog(null, "Added Successfully!");
                t1.setText(" ");
                t2.setText(" ");
                t3.setText(" ");
                t4.setText(" ");
                t5.setText(" ");
                

                
            
            
            
        } catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        // TODO add your handling code here:
        String URL = "jdbc:derby://localhost:1527/C:/Database/SAdb";
        String query = "UPDATE STUDENT SET fname=?, lname=?, email=?, contactnumber=? WHERE Stud_ID=?";
        
        try{
            Connection z = DriverManager.getConnection(URL);
            PreparedStatement p = z.prepareStatement(query);
            
            p.setString(5, t1.getText());
            p.setString(1, t2.getText());
            p.setString(2, t3.getText());
            p.setString(3, t4.getText());
            p.setString(4, t5.getText());
            
            p.executeUpdate();
            JOptionPane.showMessageDialog(null, "Update Successfully!");
                t1.setText(" ");
                t2.setText(" ");
                t3.setText(" ");
                t4.setText(" ");
                t5.setText(" ");
                

                
            
            
            
        } catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jb2ActionPerformed

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
        // TODO add your handling code here:
        String URL = "jdbc:derby://localhost:1527/C:/Database/SAdb";
        String query = "Delete from STUDENT where STUD_ID=? ";
        
         try{
            Connection z = DriverManager.getConnection(URL);
            PreparedStatement p = z.prepareStatement(query);
            
            p.setString(1, t1.getText());
          
            p.executeUpdate();
            JOptionPane.showMessageDialog(null, "Delete Successfully!");
    
            
        } catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
        }
        
        
        
    }//GEN-LAST:event_jb3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(j3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(j3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(j3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(j3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new j3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JSTUDENT;
    private javax.swing.JLabel jBackground;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JButton jb4;
    private javax.swing.JLabel ju1;
    private javax.swing.JLabel ju2;
    private javax.swing.JLabel ju3;
    private javax.swing.JLabel ju4;
    private javax.swing.JLabel ju5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
